; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -unify-loop-exits -S | FileCheck %s

; Loop consists of A, B and C:
; - A is the header
; - A and C are exiting blocks
; - B is an "internal" block that dominates exiting block C
; - D and return are exit blocks.

; Pattern: Value (%tmp41) defined in internal block (B) and used in an
;          exit block (D).

define i32 @foo(i32* %arg1, i32* %arg2) local_unnamed_addr align 2 {
; CHECK-LABEL: @foo(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP42:%.*]] = load i32, i32* [[ARG1:%.*]], align 4
; CHECK-NEXT:    br label %A
; CHECK:       A:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp slt i32 [[TMP42]], 0
; CHECK-NEXT:    br i1 [[CMP1]], label %B, label [[LOOPEXITBLOCK:%.*]]
; CHECK:       B:
; CHECK-NEXT:    [[TMP41:%.*]] = load i32, i32* [[ARG2:%.*]], align 4
; CHECK-NEXT:    br label %C
; CHECK:       C:
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP42]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %A, label [[LOOPEXITBLOCK]]
; CHECK:       D:
; CHECK-NEXT:    [[INC:%.*]] = add i32 [[TMP41_MOVED:%.*]], 1
; CHECK-NEXT:    br label %return
; CHECK:       return:
; CHECK-NEXT:    ret i32 0
; CHECK:       LoopExitBlock:
; CHECK-NEXT:    [[TMP41_MOVED]] = phi i32 [ undef, %A ], [ [[TMP41]], %C ]
; CHECK-NEXT:    [[LOOPEXITGUARDRETURN:%.*]] = phi i1 [ true, %A ], [ false, %C ]
; CHECK-NEXT:    br i1 [[LOOPEXITGUARDRETURN]], label %return, label %D
;
entry:
  %tmp42 = load i32, i32* %arg1, align 4
  br label %A

A:                                       ; preds = %B, %A.lr.ph
  %cmp1 = icmp slt i32 %tmp42, 0
  br i1 %cmp1, label %B, label %return

B:                                           ; preds = %A
  %tmp41 = load i32, i32* %arg2, align 4
  br label %C

C:
  %cmp = icmp slt i32 %tmp42, 0
  br i1 %cmp, label %A, label %D

D:
  %inc = add i32 %tmp41, 1
  br label %return

return:                                           ; preds = %B38, %A
  ret i32 0
}
