; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -unify-loop-exits -S | FileCheck %s

define void @loop_1(i1 %PredEntry, i1 %PredB, i1 %PredC, i1 %PredD) {
; CHECK-LABEL: @loop_1(
; CHECK-NEXT:  entry:
; CHECK:    br i1 %PredEntry, label %A, label %G
; CHECK:       A:
; CHECK-NEXT:    br label %B
; CHECK:       B:
; CHECK-NEXT:    br i1 %PredB, label %C, label %[[LOOPEXITBLOCK:.*]]
; CHECK:       C:
; CHECK-NEXT:    br i1 %PredC, label %D, label %[[LOOPEXITBLOCK]]
; CHECK:       D:
; CHECK-NEXT:    br i1 %PredD, label %A, label %[[LOOPEXITBLOCK]]
; CHECK:       E:
; CHECK-NEXT:    br label %exit
; CHECK:       F:
; CHECK-NEXT:    br label %exit
; CHECK:       G:
; CHECK-NEXT:    br label %F
; CHECK:       exit:
; CHECK-NEXT:    ret void
; CHECK:       [[LOOPEXITBLOCK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ true, %B ], [ false, %C ], [ false, %D ]
; CHECK-NEXT:    br i1 [[TMP0]], label %E, label %F
;
entry:
  br i1 %PredEntry, label %A, label %G

A:                                                ; preds = %D, %entry
  br label %B

B:                                                ; preds = %A
  br i1 %PredB, label %C, label %E

C:                                                ; preds = %B
  br i1 %PredC, label %D, label %F

D:                                                ; preds = %C
  br i1 %PredD, label %A, label %F

E:                                                ; preds = %B
  br label %exit

F:                                                ; preds = %G, %D, %C
  br label %exit

G:                                                ; preds = %entry
  br label %F

exit:                                             ; preds = %F, %E
  ret void
}
